### ISSUE TITLE
Notification not shown when restart phone

### ISSUE THREAD

**Issue by keyvannorouzi72** [chabokpush/chabok-client-android#18]
When I restart my phone Notification not shown until my application first run !

**Comment by Husseinhj** [comment]
Did you test this in our [starter project](https://github.com/chabokpush/chabok-starter-android)?

Please, check this with our [starter project](https://github.com/chabokpush/chabok-starter-android) if still has this issue keep me updated, otherwise check your code did you miss any thing?

What is the android version and device model?

**Comment by keyvannorouzi72** [comment]
I use Sony Xperia X whith android 8.0 ,i'll check the starter project and leave comment

**Comment by keyvannorouzi72** [comment]
I cloned your starter project and when I close the application no notification comes !
I test it on Sony Xpeira X (android 8.0) and Samsung Galaxy J1 mini prime (android 6)

**Comment by Husseinhj** [comment]
Did you use your account **appId**, **apiKey**, **username**, **password**?
Set your account config to starter project with **senderId** and also _android push notification_ should be configured in the chabok panel.

**Comment by keyvannorouzi72** [comment]
i use the default values in project , it receive notification when app is open or in background but when app closed from task manager nothing shown until open application

**Comment by Husseinhj** [comment]
The android push notification changed by the users because the starter account is just for testing and all feature is open to use it. 

I recommend using your account config to test the push notification. Also now I did change the android notification config in starter panel and ready to get the notification when the app is kill.

**Comment by keyvannorouzi72** [comment]
I checked the starter project with own account values ,when i restart phone its ok on android 6 but not ok on android 8.0 !

**Comment by Husseinhj** [comment]
I got an email with your last comment and it doesn't exist right now 🤔: 
> I checked the starter project with own account values when I restart phone its ok on android 6 but not ok on android 8.0!

I tested on  the Sony Xperia XZ Premium (the Android 8) and it works.

**Comment by keyvannorouzi72** [comment]
Notification comes with delay and its reason I deleted my comment ,sometimes notification comes and suddenly it'll be gone ,do you know whats this problem for ?

**Comment by Husseinhj** [comment]
> Notification comes with delay

[This is broadcast once](https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED), after the user has finished booting. It can be used to perform application-specific initialization, such as installing alarms. After completing the boot google start connecting to the google FCM/GCM it may take some times after booting.

> sometimes notification comes and suddenly it'll be gone

What do you mean it'll be gone? did you use `resetBadge` method in **application** class in `onCreate` method?

Did you test this in the starter project?

If your problem is fixed close the issue and create a new issue.
